task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TagCreateView,
    TaskUpdateView,
    TagUpdateView,
    TaskDeleteView,
    TagDeleteView,
    task_complete_undo
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tags"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path("task/<int:pk>/complete/", task_complete_undo, name="task-complete-undo"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "task"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    task_done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return self.content

task/forms.py
from django import forms

from task.models import Task, Tag


class TaskCreateForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )

    class Meta:
        model = Task
        fields = ("content", "deadline", "task_done", "tags")


class TagCreateForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = "__all__"

task/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskCreateForm, TagCreateForm
from task.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 4
    template_name = "task/index.html"

    def get_queryset(self):
        queryset = Task.objects.order_by("task_done")
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context["list_tasks"] = context["object_list"]

        return context


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 4
    template_name = "task/tags.html"

    def get_queryset(self):
        queryset = Tag.objects.all()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context["tags_list"] = context["object_list"]

        return context


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "task/task_form.html"
    success_url = reverse_lazy("task:index")
    form_class = TaskCreateForm


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = "task/tag_form.html"
    success_url = reverse_lazy("task:tags")
    form_class = TagCreateForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("task:index")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagCreateForm
    success_url = reverse_lazy("task:tags")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:index")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tags")


def task_complete_undo(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.task_done = not task.task_done
    task.save()
    return redirect("task:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo list</title>{% endblock %}
    <meta charset="utf-8">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}


</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<br>
<ul class="sidebar-nav list-group">
    <li class="list-group-item"><a href="{% url 'task:index'%}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'task:tags'%}">Tags</a></li>
</ul>

templates/task/index.html
{% extends "base.html" %}
{% block content %}
    <h1>
      TODO list

      <a
      style="float: right" href="{% url 'task:task-create' %}">
      <input class="btn btn-primary" type="submit" value="Add task">
      </a>
    </h1>

<br>
    {% for task in list_tasks %}

       <h5>

          <strong>{{ task.content }}</strong>
         {% if task.task_done %}
         <span class="text-success">Done</span>
         <a style="float: right" href="{% url 'task:task-complete-undo' pk=task.id %}" class="btn btn-secondary">undo</a>

         {% else %}
         <span class="text-danger">Not Done</span>
         <a style="float: right" href="{% url 'task:task-complete-undo' pk=task.id %}" class="btn btn-success">complete</a>

         {% endif %}
       </h5>
<br>

        <p class="fst-italic">
          Created: {{ task.created }}
          <span class="text-danger">Deadline: {{ task.deadline }}</span>
        </p>
          Tags: {% for tag in task.tags.all %}{{ tag }} {% endfor %}
          <a href="{% url 'task:task-update' pk=task.id %}">
          <input class="btn btn-secondary" type="submit" value="update"></a>
          <a href="{% url 'task:task-delete' pk=task.id %}">
          <input class="btn btn-danger" type="submit" value="delete"></a>
        </p>
<hr>
    {% endfor %}
{% endblock %}

templates/task/tag_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletion page {% endblock %}


{% block content %}
<br><br><br>
  <div class="card card-body blur shadow-blur mx-3 mx-lg-4 mt-n1"  >

    <h1>Delete tag from system?</h1>
      <form action="" method="post">
        {% csrf_token %}

      ` <input type="submit" value="Yes" class="btn btn-danger">
      </form>
  </div>

{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tags.html
{% extends "base.html" %}
{% block content %}

    <h1>
      Tags
      <a
      style="float: right" href="{% url 'task:tag-create' %}">
      <input class="btn btn-primary" type="submit" value="Add tag">
      </a>
    </h1>
<br>
<hr>

  {% if tags_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tags_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>

          <td>
            <a
      href="{% url 'task:tag-update' pk=tag.id %}">
      <input class="btn btn-secondary" type="submit" value="Update">
      </a>
            </td>
            <td>
            <a
      href="{% url 'task:tag-delete' pk=tag.id %}">
      <input class="btn btn-secondary" type="submit" value="delete">
      </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletion page {% endblock %}


{% block content %}
<br><br><br>
  <div class="card card-body blur shadow-blur mx-3 mx-lg-4 mt-n1" >

    <h1>Delete task from system?</h1>
      <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      </form>
  </div>

{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}